new GuiControl(multiInterpolateOptions) {
	profile = "GuiDefaultProfile";
	horizSizing = "center";
	vertSizing = "center";
	position = "0 0";
	extent = "304 295";
	visible = "1";
	new ShellTabButton(MIN_WeaponsTab) {
		profile = "ShellTabProfile";
		position = "0 0";
		extent = "108 38";
		visible = "1";
		command = "MIN_WeaponsTab.setValue(true); MIN_VehiclesTab.setValue(false); MIN_TurretsTab.setValue(false); multiInterpolateOptions.SelectTab(Weapons);";
		text = "WEAPONS";
	};
	new ShellTabButton(MIN_VehiclesTab) {
		profile = "ShellTabProfile";
		position = "0 30";
		extent = "108 38";
		visible = "1";
		command = "MIN_WeaponsTab.setValue(false); MIN_VehiclesTab.setValue(true); MIN_TurretsTab.setValue(false); multiInterpolateOptions.SelectTab(Vehicles);";
		text = "VEHICLES";
	};
	new ShellTabButton(MIN_TurretsTab) {
		profile = "ShellTabProfile";
		position = "0 60";
		extent = "108 38";
		visible = "1";
		command = "MIN_WeaponsTab.setValue(false); MIN_VehiclesTab.setValue(false); MIN_TurretsTab.setValue(true); multiInterpolateOptions.SelectTab(Turrets);";
		text = "TURRETS";
	};
	new ShellTabFrame() {
		profile = "ShellTabFrameProfile";
		position = "105 2";
		extent = "300 293";
		minextent = "8 8";
		visible = "1";
		isVertical = "1";
	};
	new ShellFieldCtrl() {
		profile = "ShellFieldProfile";
		horizSizing = "right";
		vertSizing = "bottom";
		position = "114 10";
		extent = "190 275";
		minExtent = "16 18";
		visible = "1";
		new ShellPopupMenu(multiIntPopup) {
			profile = "ShellPopupProfile";
			horizSizing = "right";
			vertSizing = "bottom";
			position = "6 5";
			extent = "180 36";
			minExtent = "49 36";
			visible = "1";
			hideCursor = "0";
			bypassHideCursor = "0";
			helpTag = "0";
			text = "select weapon";
			longTextBuffer = "1";
			maxLength = "255";
			maxPopupHeight = "500";
			buttonBitmap = "gui/shll_pulldown";
			rolloverBarBitmap = "gui/shll_pulldownbar_rol";
			selectedBarBitmap = "gui/shll_pulldownbar_act";
			noButtonStyle = "0";
		};
		new GuiTextCtrl() {
			profile = "GuiDefaultProfile";
			position = "10 60";
			extent = "100 20";
			visible = "1";
			text = "maxLatencyTicks";
		};
		new ShellTextEditCtrl(maxLatencyTicks) {
			profile = "NewTextEditProfile";
			horizSizing = "right";
			vertSizing = "bottom";
			position = "110 50";
			extent = "80 38";
			minExtent = "32 38";
			visible = "1";
			hideCursor = "0";
			bypassHideCursor = "0";
			command = "multiInterpolateOptions.SetOption(\"new\");";
			helpTag = "0";
			longTextBuffer = "0";
			maxLength = "255";
			historySize = "0";
			password = "0";
			IRCName = "0";
			tabComplete = "0";
			deniedSound = "InputDeniedSound";
			glowOffset = "9 9";
		};
		new GuiTextCtrl() {
			profile = "GuiDefaultProfile";
			position = "10 90";
			extent = "100 20";
			visible = "1";
			text = "maxPredictionTicks";
		};
		new ShellTextEditCtrl(maxPredictionTicks) {
			profile = "NewTextEditProfile";
			horizSizing = "right";
			vertSizing = "bottom";
			position = "110 80";
			extent = "80 38";
			minExtent = "32 38";
			visible = "1";
			hideCursor = "0";
			bypassHideCursor = "0";
			command = "multiInterpolateOptions.SetOption(\"new\");";
			helpTag = "0";
			longTextBuffer = "0";
			maxLength = "255";
			historySize = "0";
			password = "0";
			IRCName = "0";
			tabComplete = "0";
			deniedSound = "InputDeniedSound";
			glowOffset = "9 9";
		};
		new GuiTextCtrl() {
			profile = "GuiDefaultProfile";
			position = "10 120";
			extent = "100 20";
			visible = "1";
			text = "maxWarpTicks";
		};
		new ShellTextEditCtrl(maxWarpTicks) {
			profile = "NewTextEditProfile";
			horizSizing = "right";
			vertSizing = "bottom";
			position = "110 110";
			extent = "80 38";
			minExtent = "32 38";
			visible = "1";
			hideCursor = "0";
			bypassHideCursor = "0";
			command = "multiInterpolateOptions.SetOption(\"new\");";
			helpTag = "0";
			longTextBuffer = "0";
			maxLength = "255";
			historySize = "0";
			password = "0";
			IRCName = "0";
			tabComplete = "0";
			deniedSound = "InputDeniedSound";
			glowOffset = "9 9";
		};
		new GuiTextCtrl() {
			profile = "GuiDefaultProfile";
			position = "10 150";
			extent = "100 20";
			visible = "1";
			text = "minWarpTicks";
		};
		new ShellTextEditCtrl(minWarpTicks) {
			profile = "NewTextEditProfile";
			horizSizing = "right";
			vertSizing = "bottom";
			position = "110 140";
			extent = "80 38";
			minExtent = "32 38";
			visible = "1";
			hideCursor = "0";
			bypassHideCursor = "0";
			command = "multiInterpolateOptions.SetOption(\"new\");";
			helpTag = "0";
			longTextBuffer = "0";
			maxLength = "255";
			historySize = "0";
			password = "0";
			IRCName = "0";
			tabComplete = "0";
			deniedSound = "InputDeniedSound";
			glowOffset = "9 9";
		};
		new ShellToggleButton(ChangeOnFire) {
			profile = "ShellRadioProfile";
			horizSizing = "center";
			vertSizing = "bottom";
			position = "0 175";
			extent = "120 38";
			visible = "1";
			command = "multiInterpolateOptions.SetOption(\"new\"); DefaultOnFire.setvalue(0);";
			variable = "$ChangeOnFire";
			text = "Change on Fire";
		};
		new ShellToggleButton(DefaultOnFire) {
			profile = "ShellRadioProfile";
			horizSizing = "center";
			vertSizing = "bottom";
			position = "0 200";
			extent = "120 38";
			visible = "1";
			command = "multiInterpolateOptions.SetOption(\"new\"); ChangeOnFire.setvalue(0);";
			variable = "$DefaultOnFire";
			text = "Default on Fire";
		};
		new ShellBitmapButton() {
			profile = "ShellButtonProfile";
			horizSizing = "center";
			vertSizing = "bottom";
			position = "0 230";
			extent = "82 38";
			visible = "1";
			command = "multiInterpolateOptions.SetOption(\"default\");";
			text = "Default";
		};
	};
};