/**
 * Write the cast contract as a JSON Schema.
 *
 *   npm run cast:export-schema
 *
 * Reads src/director/castContract.ts and writes generated/cast.schema.json.
 * CastGenius imports that file (its `cast:import-schema`) to produce
 * its types, its validator, and the field guide its model reads — the
 * JSDoc in the contract is the documentation, so write it for that
 * reader.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { createGenerator } from "ts-json-schema-generator";
import { CAST_CONTRACT_VERSION } from "../src/director/castContract";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "generated", "cast.schema.json");

const schema = createGenerator({
  path: path.join(ROOT, "src/director/castContract.ts"),
  tsconfig: path.join(ROOT, "tsconfig.app.json"),
  type: "CastPlan",
  // Descriptions are the point. `extended` keeps them on every node.
  jsDoc: "extended",
  // A cast.json carries the director's camera internals alongside the
  // contract; consumers ignore them, so validation must too.
  additionalProperties: true,
  expose: "export",
  topRef: true,
  skipTypeCheck: true,
}).createSchema("CastPlan");

const out = {
  $schema: schema.$schema,
  $comment: `Cast contract v${CAST_CONTRACT_VERSION}. Generated by scripts/export-cast-schema.ts from src/director/castContract.ts — edit that, not this.`,
  ...schema,
};
await fs.mkdir(path.dirname(OUT), { recursive: true });
await fs.writeFile(OUT, JSON.stringify(out, null, 2) + "\n");
console.log(
  `wrote ${path.relative(ROOT, OUT)} (contract v${CAST_CONTRACT_VERSION}, ${Object.keys(schema.definitions ?? {}).length} definitions)`,
);
