export interface ConnectionRetryPolicy {
  cooldownMs: number;
  autoRetry: boolean;
}

interface ConnectionRetryRule extends ConnectionRetryPolicy {
  reasons: readonly RegExp[];
}

/**
 * Edit these rules to customize failed joins and reconnections. First match wins.
 * Cooldowns apply to every join, even when autoRetry is false. Avoid g/y regex flags.
 */
export const CONNECTION_RETRY_POLICIES: readonly ConnectionRetryRule[] = [
  {
    // Tribes2.exe 25034, FUN_005c0880: ChallengeReject string at 0x00798c2c:
    // "Server is cycling missions.  Please try to connect in a moment."
    reasons: [
      /^Server is cycling missions\. {2}Please try to connect in a moment\.$/i,
    ],
    cooldownMs: 5_000,
    autoRetry: true,
  },
  {
    reasons: [
      // Generated by GameConnection's handshake timeout.
      /^Connection timed out$/i,
      // Node/OS error codes, not Tribes 2 server rejection strings.
      /\b(?:ECONNREFUSED|ETIMEDOUT|EHOSTUNREACH|ENETUNREACH|ENOTFOUND|EAI_AGAIN)\b/i,
    ],
    cooldownMs: 10_000,
    autoRetry: false,
  },
  {
    // Generated by GameConnection's receive-window stall detector.
    reasons: [/^Connection stalled$/i],
    cooldownMs: 30_000,
    autoRetry: true,
  },
];

/** Includes bans, password/authentication failures, and unknown reasons/codes. */
export const DEFAULT_CONNECTION_RETRY_POLICY: ConnectionRetryPolicy = {
  cooldownMs: 30_000,
  autoRetry: false,
};

export function getConnectionRetryPolicy(
  reason: string | undefined,
): ConnectionRetryPolicy {
  // The UI also checks status text decorated by shared.retryStatusMessage.
  const message = (reason?.trim() ?? "").replace(
    / — retrying \(\d+\/\d+\)\.\.\.$/,
    "",
  );
  return (
    CONNECTION_RETRY_POLICIES.find((rule) =>
      rule.reasons.some((match) => match.test(message)),
    ) ?? DEFAULT_CONNECTION_RETRY_POLICY
  );
}

/** Keep OS error codes available to policy matching and status messages. */
export function connectionErrorReason(error: unknown): string {
  if (!(error instanceof Error)) return String(error);
  const code = (error as Error & { code?: unknown }).code;
  return typeof code === "string" && code && !error.message.includes(code)
    ? `${code}: ${error.message}`
    : error.message;
}
